import Mathlib
import Mathlib.RingTheory.UniqueFactorizationDomain.NormalizedFactors

open Polynomial

/-!
# Introduction 1.0: Global-field vocabulary

The lecture opens by packaging the standard ambient objects that motivate the rest
of Chapter 1: prime fields, number fields, the `F_q[t]`/`ℤ` analogy, and global
function fields. Mathlib already bundles these notions through characteristic-based
algebra maps, `NumberField`, `AdjoinRoot`, `RatFunc`, and `FunctionField`.

The final paragraph of the blob surveys completions and local fields. That material
belongs to the later valuation/completion development, so it remains commentary here
rather than blocking the current Stage 3.1 scaffold.
-/

namespace SutherlandNumberTheoryLecture1
namespace Chapter1

section Introduction_01_00

variable (K : Type*) [Field K]

/-- The lecture's ambient starting ring `ℤ` is a principal ideal domain. -/
theorem int_isPID : IsPrincipalIdealRing ℤ := by
  infer_instance

/-- The lecture's field of fractions of `ℤ` is Mathlib's `ℚ`. -/
theorem int_fractionRing_isRat : IsFractionRing ℤ ℚ := by
  infer_instance

/-- The lecture's invocation of the fundamental theorem of arithmetic can be recorded
via the normalized prime factors of a nonzero integer. -/
theorem int_prime_factorization_via_normalizedFactors
    (n : ℤ) (hn : n ≠ 0) :
    (∀ p ∈ UniqueFactorizationMonoid.normalizedFactors n, Prime p) ∧
      Associated (UniqueFactorizationMonoid.normalizedFactors n).prod n := by
  refine ⟨?_, UniqueFactorizationMonoid.prod_normalizedFactors hn⟩
  intro p hp
  exact UniqueFactorizationMonoid.prime_of_normalized_factor p hp

/-- For nonzero integers, equality of normalized prime factors is the packaged
uniqueness statement "up to multiplication by a unit and reordering". -/
theorem int_associated_iff_normalizedFactors_eq
    {m n : ℤ} (hm : m ≠ 0) (hn : n ≠ 0) :
    Associated m n ↔
      UniqueFactorizationMonoid.normalizedFactors m =
        UniqueFactorizationMonoid.normalizedFactors n :=
  UniqueFactorizationMonoid.associated_iff_normalizedFactors_eq_normalizedFactors hm hn

/-- If `p` is prime, then `(p)` is a maximal ideal of `ℤ`. -/
theorem int_span_prime_isMaximal (p : ℤ) (hp : Prime p) :
    (Ideal.span ({p} : Set ℤ)).IsMaximal := by
  exact PrincipalIdealRing.isMaximal_of_irreducible (Prime.irreducible hp)

/-- Quotienting `ℤ` by the principal ideal `(p)` gives the prime field `𝔽_p`. -/
def int_quotient_span_nat_equiv_zmod (p : ℕ) :
    (ℤ ⧸ Ideal.span ({(p : ℤ)} : Set ℤ)) ≃+* ZMod p := by
  exact Int.quotientSpanNatEquivZMod p

/-- In characteristic zero, the lecture's prime field is `ℚ`. -/
theorem charZero_contains_rat [CharZero K] : Nonempty (Algebra ℚ K) := by
  exact ⟨inferInstance⟩

/-- In characteristic `p`, the lecture's prime field is `𝔽_p`, realized as `ZMod p`. -/
theorem charP_contains_zmod (p : ℕ) [Fact p.Prime] [CharP K p] :
    Nonempty (Algebra (ZMod p) K) := by
  letI : Algebra (ZMod p) K := ZMod.algebra K p
  exact ⟨inferInstance⟩

/-- A bundled number field is, by definition, a finite extension of `ℚ`. -/
theorem numberField_isFiniteExtension [NumberField K] : FiniteDimensional ℚ K := by
  infer_instance

/-- The lecture's quotients `ℚ[X]/(f)` by irreducibles are fields in Mathlib via `AdjoinRoot`. -/
theorem quotientByIrreducibleField (f : Polynomial ℚ) [Fact (Irreducible f)] :
    Nonempty (Field (AdjoinRoot f)) := by
  exact ⟨inferInstance⟩

/-- These irreducible polynomial quotients are the lecture's basic examples of number fields. -/
theorem quotient_by_irreducible_isNumberField (f : Polynomial ℚ) [Fact (Irreducible f)] :
    NumberField (AdjoinRoot f) := by
  infer_instance

/-- The lecture's presentation of number fields uses that `ℚ[X]` is a PID. -/
theorem rational_polynomial_isPID : IsPrincipalIdealRing (Polynomial ℚ) := by
  infer_instance

/-- Over a field, irreducible polynomials generate maximal ideals, matching the quotient
presentation used for the lecture's number-field examples. -/
theorem irreducible_generates_maximal_ideal_over_rat
    (f : Polynomial ℚ) [Fact (Irreducible f)] :
    (Ideal.span ({f} : Set (Polynomial ℚ))).IsMaximal := by
  exact PrincipalIdealRing.isMaximal_of_irreducible (Fact.out : Irreducible f)

/-- Every number field admits the quotient presentation promised in the lecture:
it is generated by one element and therefore isomorphic to `ℚ[X]/(f)` for the
minimal polynomial of that generator. -/
theorem numberField_exists_irreducible_quotient_presentation [NumberField K] :
    ∃ f : Polynomial ℚ, f.Monic ∧ Irreducible f ∧ Nonempty (K ≃ₐ[ℚ] AdjoinRoot f) := by
  let pb : PowerBasis ℚ K := Field.powerBasisOfFiniteOfSeparable ℚ K
  refine ⟨minpoly ℚ pb.gen, minpoly.monic pb.isIntegral_gen,
    minpoly.irreducible pb.isIntegral_gen, ?_⟩
  refine ⟨pb.equivAdjoinSimple.symm.trans ?_⟩
  exact (IntermediateField.adjoinRootEquivAdjoin ℚ pb.isIntegral_gen).symm

variable (Fq F : Type*) [Field Fq] [Field F] [Algebra (RatFunc Fq) F]

/-- Mathlib's `FunctionField` predicate packages the lecture's definition of a global function
field as a finite extension of `F_q(t)`. -/
theorem globalFunctionField_isFiniteExtension [FunctionField Fq F] :
    FiniteDimensional (RatFunc Fq) F := by
  infer_instance

/-- The `F_q[t]` side of the lecture's analogy uses the standard PID instance for polynomial
rings over fields. -/
theorem polynomial_over_field_isPID : IsPrincipalIdealRing (Polynomial Fq) := by
  infer_instance

/-- The lecture's "dimension one" slogan for `F_q[t]` is already packaged in Mathlib as the
Krull-dimension bound for principal ideal domains. -/
theorem polynomial_over_field_krullDimLEOne :
    Ring.KrullDimLE 1 (Polynomial Fq) := by
  infer_instance

/-- Quotients of `F_q[t]` by irreducibles are fields, matching the residue-field part of the
lecture's `F_q[t]` versus `ℤ` analogy. -/
theorem quotientByIrreducibleOverFunctionFieldBaseField
    (f : Polynomial Fq) [Fact (Irreducible f)] : Nonempty (Field (AdjoinRoot f)) := by
  exact ⟨inferInstance⟩

/-- When the coefficient field is finite, the lecture further records these residue fields as
finite fields. We isolate that claim here for later proof refinement. -/
theorem quotient_by_irreducible_over_finite_field_isFinite
    [Finite Fq] (f : Polynomial Fq) [Fact (Irreducible f)] : Finite (AdjoinRoot f) := by
  let hf : f ≠ 0 := (Fact.out : Irreducible f).ne_zero
  let pb := AdjoinRoot.powerBasis hf
  letI : Fintype Fq := Fintype.ofFinite Fq
  letI : Fintype (AdjoinRoot f) := Module.fintypeOfFintype pb.basis
  exact Finite.of_fintype _

/-- The lecture sharpens the previous residue-field claim by identifying the quotient with a
finite field of size `q^d`, where `q = |F_q|` and `d = deg f`. -/
theorem quotient_by_irreducible_over_finite_field_card
    [Finite Fq] (f : Polynomial Fq) [Fact (Irreducible f)] :
    Nat.card (AdjoinRoot f) = Nat.card Fq ^ f.natDegree := by
  let hf : f ≠ 0 := (Fact.out : Irreducible f).ne_zero
  let pb := AdjoinRoot.powerBasis hf
  letI : Module.Finite Fq (AdjoinRoot f) := pb.finite
  calc
    Nat.card (AdjoinRoot f) = Nat.card Fq ^ Module.finrank Fq (AdjoinRoot f) :=
      Module.natCard_eq_pow_finrank (K := Fq) (V := AdjoinRoot f)
    _ = Nat.card Fq ^ pb.dim := by
      rw [PowerBasis.finrank (R := Fq) (S := AdjoinRoot f) pb]
    _ = Nat.card Fq ^ f.natDegree := by
      rfl

/-- Every residue field `F_q[t]/(f)` has the same characteristic as the base field `F_q`,
so also the same characteristic as its fraction field `F_q(t)`. -/
theorem adjoinRoot_char_eq_baseField_char
    (f : Polynomial Fq) [Fact (Irreducible f)] :
    ringChar (AdjoinRoot f) = ringChar Fq := by
  simpa using (Algebra.ringChar_eq Fq (AdjoinRoot f)).symm

end Introduction_01_00

end Chapter1
end SutherlandNumberTheoryLecture1
