import SutherlandNumberTheoryLecture1.Chapter1.«01_10_Definition»
import SutherlandNumberTheoryLecture1.Chapter1.«01_10a_Discussion»
import SutherlandNumberTheoryLecture1.Chapter1.«01_11_Definition»

/-!
# Discussion 1.11a: structural consequences of a discrete valuation

This blob records the lecture's standard structure package for a discrete
valuation ring: existence of a uniformizer, unit-times-power factorization in
the fraction field, the classification of ideals by valuation, total ordering
of ideals, and the maximal ideal cut out by strictly positive valuation.
-/

namespace SutherlandNumberTheoryLecture1
namespace Chapter1

section Discussion_01_11a

open scoped BigOperators

variable {k : Type*} [Field k]
variable (v : RealValuation k)
variable [IsCyclic (MonoidWithZeroHom.valueGroup (asValuation v))]
variable [Nontrivial (MonoidWithZeroHom.valueGroup (asValuation v))]

/-- A discrete valuation ring admits a uniformizer. -/
theorem exists_uniformizer :
    ∃ π : valuationSubring v, Irreducible π := by
  simpa using (IsDiscreteValuationRing.exists_irreducible (valuationSubring v))

/-- Any two uniformizers differ by multiplication by a unit. -/
theorem associated_of_uniformizer {π π' : valuationSubring v}
    (hπ : Irreducible π) (hπ' : Irreducible π') :
    Associated π π' := by
  simpa using
    (IsDiscreteValuationRing.associated_of_irreducible (R := valuationSubring v) hπ hπ')

/-- The lecture's `x = u * π^n` factorization for nonzero elements of the fraction field. -/
theorem exists_unique_unit_mul_uniformizer_zpow (π : valuationSubring v) (hπ : Irreducible π)
    (x : kˣ) :
    ∃! un : Units (valuationSubring v) × ℤ,
      (x : k) =
        ((((un.1 : Units (valuationSubring v)) : valuationSubring v) : k) *
          (((π : valuationSubring v) : k) ^ un.2)) := by
  sorry

/-- A DVR is a principal ideal ring, hence the lecture's PID conclusion holds. -/
theorem valuationSubring_isPrincipalIdealRing :
    IsPrincipalIdealRing (valuationSubring v) := by
  infer_instance

/-- The principal ideal generated by a power of a uniformizer is the valuation cutoff locus. -/
theorem span_pow_uniformizer_eq_valuation_ge (π : valuationSubring v) (hπ : Irreducible π)
    (n : ℕ) :
    (((Ideal.span ({π ^ n} : Set (valuationSubring v))) : Ideal (valuationSubring v)) :
        Set (valuationSubring v)) =
      {a : valuationSubring v | (((n : ℝ) : WithTop ℝ) ≤ v (a : k))} := by
  sorry

/-- The ideal generated by `π^n` depends only on `n`, not on the chosen uniformizer. -/
theorem span_pow_uniformizer_eq_span_pow_uniformizer
    {π π' : valuationSubring v} (hπ : Irreducible π) (hπ' : Irreducible π') (n : ℕ) :
    Ideal.span ({π ^ n} : Set (valuationSubring v)) =
      Ideal.span ({π' ^ n} : Set (valuationSubring v)) := by
  sorry

/-- Every nonzero ideal is a power of the maximal ideal, equivalently a power of a uniformizer. -/
theorem exists_eq_span_pow_uniformizer_of_ne_bot (I : Ideal (valuationSubring v)) (hI : I ≠ ⊥) :
    ∃ π : valuationSubring v, Irreducible π ∧ ∃ n : ℕ, I = Ideal.span ({π ^ n} : Set _) := by
  sorry

/-- The ideals of a DVR are linearly ordered by inclusion. -/
theorem ideals_are_totally_ordered (I J : Ideal (valuationSubring v)) :
    I ≤ J ∨ J ≤ I := by
  sorry

/-- A uniformizer generates the unique maximal ideal. -/
theorem maximalIdeal_eq_span_uniformizer (π : valuationSubring v) (hπ : Irreducible π) :
    IsLocalRing.maximalIdeal (valuationSubring v) =
      Ideal.span ({π} : Set (valuationSubring v)) := by
  simpa [IsDiscreteValuationRing.irreducible_iff_uniformizer] using hπ.maximalIdeal_eq

/-- The unique maximal ideal is cut out by strictly positive valuation. -/
theorem maximalIdeal_eq_positive_valuation_locus :
    (((IsLocalRing.maximalIdeal (valuationSubring v)) : Ideal (valuationSubring v)) :
        Set (valuationSubring v)) =
      {a : valuationSubring v | 0 < v (a : k)} := by
  ext a
  simpa using mem_maximalIdeal_iff_valuation_pos (v := v) a

/-- The maximal ideal of a DVR is the only maximal ideal. -/
theorem eq_maximalIdeal_of_isMaximal {I : Ideal (valuationSubring v)} (hI : I.IsMaximal) :
    I = IsLocalRing.maximalIdeal (valuationSubring v) := by
  sorry

end Discussion_01_11a

end Chapter1
end SutherlandNumberTheoryLecture1
