import Mathlib

/-!
# Example 1.14: the `p`-adic valuation ring on `ℚ`

The lecture identifies the valuation ring of the `p`-adic valuation with the
localization `ℤ_(p)`, describes its maximal ideal as `(p)`, and notes that its
residue field is `𝔽_p`. Mathlib already packages the localization-at-a-prime
construction and the local residue field, so this file records the example as a
small bundle of explicit declarations.
-/

namespace SutherlandNumberTheoryLecture1
namespace Chapter1

section Example_01_14

variable (p : ℕ) [Fact p.Prime]

instance spanSingletonIntPrimeIsPrime : (Ideal.span ({(p : ℤ)} : Set ℤ)).IsPrime := by
  rw [Ideal.span_singleton_prime (show (p : ℤ) ≠ 0 by
    exact_mod_cast (Fact.out : p.Prime).ne_zero)]
  exact Int.prime_iff_natAbs_prime.mpr (by simpa using (Fact.out : p.Prime))

/-- The lecture's `p`-adic valuation ring `ℤ_(p)` is the localization of `ℤ` at `(p)`. -/
abbrev padicValuationRing : Type := Localization.AtPrime (Ideal.span ({(p : ℤ)} : Set ℤ))

/-- The chosen model of `ℤ_(p)` is literally localization at the prime ideal `(p)`. -/
theorem padicValuationRing_isLocalization :
    IsLocalization.AtPrime (padicValuationRing p) (Ideal.span ({(p : ℤ)} : Set ℤ)) := by
  infer_instance

/-- In `ℤ_(p)`, the unique maximal ideal is generated by the image of `p`. -/
theorem padicValuationRing_maximalIdeal_eq_span_p :
    IsLocalRing.maximalIdeal (padicValuationRing p) =
      Ideal.span ({(((p : ℤ) : padicValuationRing p))} : Set (padicValuationRing p)) := by
  calc
    IsLocalRing.maximalIdeal (padicValuationRing p) =
        (Ideal.span ({(p : ℤ)} : Set ℤ)).map (algebraMap ℤ (padicValuationRing p)) := by
      symm
      exact IsLocalization.AtPrime.map_eq_maximalIdeal
        (p := Ideal.span ({(p : ℤ)} : Set ℤ)) (Rₚ := padicValuationRing p)
    _ = Ideal.span ({(((p : ℤ) : padicValuationRing p))} : Set (padicValuationRing p)) := by
      simp [Ideal.map_span]

/-- The residue field of `ℤ_(p)` is `𝔽_p`, modeled in Mathlib as `ZMod p`. -/
theorem padicValuationRing_residueField_equiv_zmod :
    Nonempty (IsLocalRing.ResidueField (padicValuationRing p) ≃+* ZMod p) := by
  let P : Ideal ℤ := Ideal.span ({(p : ℤ)} : Set ℤ)
  haveI : P.IsMaximal := by
    simpa [P] using (Int.ideal_span_isMaximal_of_prime p : P.IsMaximal)
  refine ⟨?_⟩
  exact
    (IsLocalization.AtPrime.equivQuotMaximalIdeal (p := P) (Rₚ := padicValuationRing p)).symm.trans
      (Int.quotientSpanNatEquivZMod p)

end Example_01_14

end Chapter1
end SutherlandNumberTheoryLecture1
